### PR TITLE
Fix: Doesn't work when more than one fk to the same table 

### PR DESCRIPTION
**Pull request by stephandesouza**
PHPUnit ok.

### CODE REVIEW

**Comment by K-Phoen** [comment]
Thanks for your PR!

Could you also add a few tests and some doc for this feature? This would be great!

**Comment by stephandesouza** [comment]
Ok @K-Phoen will work on it when its possible to me :)

**Comment by K-Phoen** [comment]
Great, thanks!
Le 3 janv. 2013 04:58, "Stephan de Souza" notifications@github.com a
écrit :

**Comment by K-Phoen** [comment]
ping @stephandesouza ?

**Comment by stephandesouza** [comment]
Oh, sorry... The project is archived, and I really forgot this issue.

Added to my bookmark, wait more 2 weeks, please! xD

**Pull request closed without merging**
